apiVersion: v1
kind: Service
metadata:
  name: web-app-service
spec:
  type: NodePort
  selector:
    app: static-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30036
